<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2bbohhh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2bbohhh/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2bbohhh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2bbohhh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2bbohhh\appProdProjectContainer([
    'container.build_hash' => '2bbohhh',
    'container.build_id' => '00f8f10a',
    'container.build_time' => 1559076046,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2bbohhh');
